plugins {
    id 'java'
    id 'application'
}

group = 'com.example.app'
version = '1.0.0-b'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // adjust if needed
    }
}

application {
    mainClass = 'com.example.app.Main' // CHANGE to your real main class
    applicationDefaultJvmArgs = ["-da"] // disable assertion
}

repositories {
    mavenCentral()
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.example.app.Main'
        )
    }
}